select 'GRANT SELECT ON ' || OWNER || '.' || OBJECT_NAME ||' TO RL_BI_GERAL_RO;' comm
  from dba_objects
 where OBJECT_TYPE in ('VIEW', 'TABLE')
   AND OWNER IN ('MST_ESTATISTICA',
                 'VVBIMSTRMDP1306_PROD',
                 'SODI',
                 'BI_STG_ALELO',
                 'REL_WEB_AUTO',
                 'VVBI00',
                 'VVBIMSTRMDP1396_PROD',
                 'VT_INT_ODS',
                 'BASE_UNICA_CAD',
                 'SI_INFORMTN_SCHEMA',
                 'OWDESP01',
                 'BI_GOV_ALELO',
                 'DQ_GS_ALELO',
                 'VVBIMSTRMD_PROD',
                 'MODI',
                 'PCREP',
                 'DQ_ALELO',
                 'BASE_BUREAU',
                 'BI_DW_ALELO2',
                 'SNPM',
                 'SNPW',
                 'SNPT',
                 'USIN86',
                 'BI_WRK_ALELO',
                 'OPS$VVBI01',
                 'BI_DW_ALELO',
                 'USR_DQT_STG',
                 'VVBI02',
                 'PCDOM',
                 'USPROC',
                 'WODI',
                 'ODSBI',
                 'USDESP01',
                 'BI_REL_ALELO ',
                 'MON_DBCENTRAL');
