set pages 1000
set lines 1000
SET HEADING ON
COLUMN OWNER  FORMAT A25
COLUMN OBJECT FORMAT A40
SELECT OWNER, OBJECT_TYPE TYPE, OBJECT_NAME OBJECT, TO_CHAR(LAST_DDL_TIME, 'DD/MM/YY HH24:MI:SS') LAST_DDL_TIME 
FROM DBA_OBJECTS 
WHERE STATUS='INVALID'
ORDER BY 1, 2, 3;
SET HEADING ON
