set pages 1000
set lines 1000
set timing off
SET UNDERLINE =
SET FEEDBACK  2
COLUMN INSTANCE_NAME FORMAT A13
COLUMN DB_STATUS     FORMAT A10
COLUMN VERSION       FORMAT A10
COLUMN HOST_NAME     FORMAT A17
COLUMN STARTUP_TIME  FORMAT A22
COLUMN ACTIVE_STATE  FORMAT A12
COLUMN date_scn      FORMAT A22
COLUMN cur_scn       FORMAT A8
COLUMN f_logging     FORMAT A10
COLUMN BLOCKED       FORMAT A5
COLUMN THREAD        FORMAT A6
COLUMN THREAD        FORMAT A4
COLUMN I_NUM         FORMAT 999
COLUMN NAME          FORMAT A8
COLUMN OPEN_MODE           FORMAT A10
COLUMN RESETLOGS_CHANGE    FORMAT 9999999999999999    HEAD 'RESETLOGS|CHANGE'    
COLUMN RESETLOGS_TIME      FORMAT A21           HEAD 'RESETLOGS TIME'    
COLUMN OPEN_RESETLOGS      FORMAT A15           HEAD 'OPEN|RESETLOGS'  
COLUMN LOG_MODE            FORMAT A11
COLUMN FLASHBACK_ON        FORMAT A9            HEAD 'FLASHBACK|ON'   JUSTIFY RIGHT
COLUMN CONTROLFILE_SEQ     FORMAT 9999999999    HEAD 'CONTROLFILE|SEQ'  
COLUMN VERSION_TIME        FORMAT A21           HEAD 'VERSION_TIME'  


set pages 100
set lines 200
COLUMN I_NUM         FORMAT 999
COLUMN INSTANCE_NAME FORMAT A13
COLUMN HOST_NAME     FORMAT A28
COLUMN VERSION       FORMAT A13
COLUMN STARTUP_TIME  FORMAT A22
COLUMN ACTIVE_STATE  FORMAT A12
COLUMN DB_STATUS     FORMAT A10
SELECT INSTANCE_NUMBER AS I_NUM,
	   A.INSTANCE_NAME INSTANCE_NAME, 
	   A.HOST_NAME HOST_NAME,
	   A.VERSION, 
	   TO_CHAR(A.STARTUP_TIME, 'DD/MM/YYYY HH24:MI:SS') STARTUP_TIME, 
	   A.ACTIVE_STATE,
	   A.DATABASE_STATUS DB_STATUS   ,
	   A.INSTANCE_ROLE
FROM GV$INSTANCE A
/
--alter session set nls_date_format = 'DD-MON-YYYY HH24:MI:SS';
SELECT  NAME
       ,OPEN_MODE
       ,RESETLOGS_CHANGE# as RESETLOGS_CHANGE
	   ,TO_CHAR(RESETLOGS_TIME,'DD/MM/YYYY HH24:MI:SS') RESETLOGS_TIME
	   ,OPEN_RESETLOGS
	   ,LOG_MODE
	   ,FORCE_LOGGING f_logging
	   ,FLASHBACK_ON
	   ,CONTROLFILE_SEQUENCE# CONTROLFILE_SEQ
	   ,TO_CHAR(VERSION_TIME,'DD/MM/YYYY HH24:MI:SS') VERSION_TIME
	   ,CREATED
FROM v$database A
/