set pages 1000
set lines 1000
COLUMN INSTANCE_NAME FORMAT A13
COLUMN DB_STATUS     FORMAT A10
COLUMN VERSION       FORMAT A10
COLUMN HOST_NAME     FORMAT A17
COLUMN STARTUP_TIME  FORMAT A22
COLUMN ACTIVE_STATE  FORMAT A12

SELECT UPPER(INSTANCE_NAME) INSTANCE_NAME, 
       UPPER(HOST_NAME) HOST_NAME,
       VERSION, 
       TO_CHAR(STARTUP_TIME, 'DD-MON-YYYY HH24:MI:SS') 
       STARTUP_TIME, 
       STATUS, 
       ARCHIVER, 
       LOGINS, 
       ACTIVE_STATE,
       DATABASE_STATUS DB_STATUS
FROM V$INSTANCE;

select * from v$version;