watch -d "netstat -anp | grep -i LISTEN | grep -i 443"

netstat -anp | grep -i LISTEN | grep -i 1565
netstat -anp | grep -i LISTEN | grep -i 152[1-2]
netstat -anp | grep -i LISTEN | grep -i 15 |grep tnslsnr

netstat -nr
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exa3-scan)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=otmproj)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.1.230)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=otmproj)))'




sqlplus 'system/manager@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=jmlwgr31.cpdqa.corpqa.jmartins.com)(PORT=1524)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=EVEPDQA)))'

sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.20.1.230)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=otmproj)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.35)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.36)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=lnxorasp-scan)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'

sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.245.9 )(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_ogg)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.245.10)(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_ogg)))'

tnsping '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.36)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PBACK)))'

tnsping '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.34)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))' 1000