watch -d "netstat -anp | grep -i LISTEN | grep -i 1521"

sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.34)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.35)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.36)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=lnxorasp-scan)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))'

sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.245.9 )(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_ogg)))'
sqlplus 'x/x@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.245.10)(PORT=1522)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_ogg)))'

tnsping '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.36)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=PBACK)))'

tnsping '(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.214.250.34)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=srv_bko_mon_flex)))' 1000



sqlplus 'DPBCK/a33pr0t3c@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=dbjr2-db-vip.cpd.corp.jmartins.com)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=jr2svc)))'

##EVEPD
sqlplus 'DPBCK/a33pr0t3c@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.134.40)(PORT=1525)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=EVEPD)))'

##EVEPD
sqlplus 'DPBCK/a33pr0t3c@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.134.40)(PORT=1525)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=EVEPD)))'


sqlplus 'DPBCK/a33pr0t3c@NOME_ENTRADA_TNSNAMES'


@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=dbjr2-dr-db-vip.cpd.corp.jmartins.com)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=jr2svc)))

a33pr0t3c

VIP                 : dbshiftp2-qa-vip-bck.cpd.corp.jmartins.com
Backup user         : DPBCK
Password            : a33pr0t3c



    execute dbms_sqltune.accept_sql_profile(task_name => 'TASK_285',task_owner => 'SYS', replace => TRUE);
