


SET LINES 300 
SET PAGES 999
COL CLIENT_NAME FOR A35
COL CONSUMER_GROUP FOR A30 
COL WINDOW_GROUP FOR A20 
COL STATUS FOR A10 
COL WINDOW_GROUP_NAME FOR A20
COL WINDOW_NAME FOR A20
SET LINES 300 
SET PAGES 999
COL WINDOW_NAME FOR A18
COL REPEAT_INTERVAL FOR A72
COL WINDOW_DURATION FOR A32
COL ENABLED FOR A10



SELECT CLIENT_NAME,
       STATUS   ,
       b.WINDOW_NAME,
       c.REPEAT_INTERVAL,
       TO_CHAR(EXTRACT(DAY FROM c.DURATION),'90') || ' Days ' || 
       TO_CHAR(EXTRACT(HOUR FROM c.DURATION),'90') || ' Hours ' ||
       TO_CHAR(EXTRACT(MINUTE FROM c.DURATION),'90') || ' Minutes ' WINDOW_DURATION,
       ENABLED 
FROM 
       DBA_AUTOTASK_CLIENT a, DBA_SCHEDULER_WINGROUP_MEMBERS b, DBA_SCHEDULER_WINDOWS c
WHERE CLIENT_NAME = 'auto optimizer stats collection'
and a.WINDOW_GROUP = b.WINDOW_GROUP_NAME 
and b.WINDOW_NAME = c.WINDOW_NAME
/
