set pages 1000
set lines 1000
set timing off
SET UNDERLINE =
SET FEEDBACK  2
COLUMN INSTANCE_NAME FORMAT A13
COLUMN DB_STATUS     FORMAT A10
COLUMN VERSION       FORMAT A10
COLUMN HOST_NAME     FORMAT A17
COLUMN STARTUP_TIME  FORMAT A22
COLUMN ACTIVE_STATE  FORMAT A12
COLUMN date_scn      FORMAT A22
COLUMN cur_scn       FORMAT A8
COLUMN f_logging     FORMAT A10
COLUMN BLOCKED       FORMAT A5
COLUMN THREAD        FORMAT A6
COLUMN THREAD        FORMAT A4
COLUMN I_NUM         FORMAT 999
COLUMN NAME          FORMAT A8
COLUMN OPEN_MODE           FORMAT A10
COLUMN RESETLOGS_CHANGE    FORMAT 9999999999999999    HEAD 'RESETLOGS|CHANGE'
COLUMN RESETLOGS_TIME      FORMAT A21           HEAD 'RESETLOGS TIME'
COLUMN OPEN_RESETLOGS      FORMAT A15           HEAD 'OPEN|RESETLOGS'
COLUMN LOG_MODE            FORMAT A11
COLUMN FLASHBACK_ON        FORMAT A9            HEAD 'FLASHBACK|ON'   JUSTIFY RIGHT
COLUMN CONTROLFILE_SEQ     FORMAT 9999999999    HEAD 'CONTROLFILE|SEQ'
COLUMN VERSION_TIME        FORMAT A21           HEAD 'VERSION_TIME'

SELECT INSTANCE_NUMBER AS I_NUM,
       UPPER(A.INSTANCE_NAME) INSTANCE_NAME,
       UPPER(A.HOST_NAME) HOST_NAME,
       A.VERSION,
       TO_CHAR(A.STARTUP_TIME, 'DD-MON-YYYY HH24:MI:SS') STARTUP_TIME,
       A.STATUS,
       A.ARCHIVER,
       A.LOGINS,
       A.ACTIVE_STATE,
       A.DATABASE_STATUS DB_STATUS   ,
           a.BLOCKED BLK,
           TO_CHAR(A.THREAD#) THREAD,
           A.SHUTDOWN_PENDING SHUT,
           A.INSTANCE_ROLE
FROM gV$INSTANCE A
/
SELECT BANNER FROM V$VERSION
/
SELECT PARAMETER, VALUE FROM V$OPTION WHERE UPPER(PARAMETER) IN 
('ACTIVE DATA GUARD', 'ADVANCED ANALYTICS', 'ADVANCED SECURITY', 'DATA MASKING PACK', 'DATABASE VAULT','LABEL SECURITY', 'OLAP', 'REAL APPLICATION TESTING', 'SPATIAL AND GRAPH')
ORDER BY 2 desc,1
/
COLUMN NAME          FORMAT A40
--EXEC DBMS_FEATURE_USAGE_INTERNAL.EXEC_DB_USAGE_SAMPLING(SYSDATE);
SELECT distinct DBID, substr(NAME,1,40) as NAME, DETECTED_USAGES, CURRENTLY_USED, FIRST_USAGE_DATE, LAST_USAGE_DATE FROM DBA_FEATURE_USAGE_STATISTICS 
where upper(NAME) like '%ACTIVE DATA GUARD%' or upper(NAME) like '%ADVANCED ANALYTICS%'
  or  upper(NAME) like '%ADVANCED SECURITY%' or upper(NAME) like '%MASKING%' 
  or  upper(NAME) like '%DATABASE VAULT%'    or upper(NAME) like '%LABEL SECURITY%'   
  or  upper(NAME) like '%OLAP%'              or upper(NAME) like '%TESTING%'        or upper(NAME) like '%SPATIAL%'   
order by 2, 1 
/
select value from v$option where parameter = 'Real Application Testing';