--
set pages 1000
set lines 1000
column command     format a100 
SELECT 'ALTER SYSTEM ARCHIVE LOG CURRENT ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM CHECKPOINT          ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM ARCHIVE LOG CURRENT ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM CHECKPOINT          ;' COMMAND FROM DUAL UNION ALL  
SELECT 'ALTER SYSTEM FLUSH SHARED_POOL   ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM FLUSH BUFFER_CACHE  ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM FLUSH GLOBAL CONTEXT;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM CHECKPOINT          ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM ARCHIVE LOG CURRENT ;' COMMAND FROM DUAL UNION ALL
SELECT 'ALTER SYSTEM CHECKPOINT          ;' COMMAND FROM DUAL 
/

