--

COLUMN PROPERTY_NAME             FORMAT a30         HEAD 'PROPERTY_NAME'
COLUMN PROPERTY_VALUE            FORMAT a30         HEAD 'PROPERTY_VALUE'

SELECT 	PROPERTY_NAME, PROPERTY_VALUE 
FROM 	DATABASE_PROPERTIES 
WHERE   PROPERTY_NAME='DEFAULT_TEMP_TABLESPACE'
/ 