-- 
set lines 3000
set pages 500
COLUMN BEGIN_INTERVAL_TIME             FORMAT a22         HEAD 'BEGIN_INTERVAL_TIME'
COLUMN END_INTERVAL_TIME               FORMAT a22         HEAD 'END_INTERVAL_TIME'
COLUMN SIZE_MB                         FORMAT 99999999    HEAD 'SIZE_MB'
COLUMN MAXSIZE_MB                      FORMAT 99999999    HEAD 'MAXSIZE_MB'
COLUMN USED_PERCENTAGE                 FORMAT 999         HEAD 'USED_PERCENTAGE %'

SELECT TO_CHAR(BEGIN_INTERVAL_TIME,'DD/MM/YYYY HH24:MI:SS') BEGIN_INTERVAL_TIME
      ,TO_CHAR(END_INTERVAL_TIME,'DD/MM/YYYY HH24:MI:SS') END_INTERVAL_TIME
      ,B.NAME
      ,ROUND((TABLESPACE_SIZE * 8 * 1024) / 1024 / 1024, 2) SIZE_MB
      ,ROUND((TABLESPACE_MAXSIZE * 8 * 1024) / 1024 / 1024, 2) MAXSIZE_MB
      ,ROUND((TABLESPACE_USEDSIZE * 8 * 1024) / 1024 / 1024, 2) USEDSIZE_MB
      ,ROUND(((TABLESPACE_USEDSIZE * 8 * 1024) / 1024 / 1024) /
             ((TABLESPACE_MAXSIZE * 8 * 1024) / 1024 / 1024) * 100,
             2) USED_PERCENTAGE
  FROM dba_hist_tbspc_space_usage A
  JOIN V$TABLESPACE B ON (A.TABLESPACE_ID = B.TS#)
  JOIN DBA_HIST_SNAPSHOT C ON (A.SNAP_ID = C.SNAP_ID)
 WHERE NAME = 'TEMP02' -- Tablespacename to check the gradual growth of particular tablespace
   AND BEGIN_INTERVAL_TIME > SYSDATE - &DAYS
 ORDER BY BEGIN_INTERVAL_TIME DESC 
/ 
 