SELECT COUNT(OT.ID_RESPONSE_CODE) QTD,
       ROUND(COUNT(OT.ID_RESPONSE_CODE) * 100 / 5000, 2) || ' %' "%",
       OT.ID_RESPONSE_CODE || ' - ' || RC.DESCRIPTION COD_RESPOSTA,
       SUM(MESSAGE_AMNT) VALOR,
       round(SUM(MESSAGE_AMNT) / COUNT(OT.ID_RESP ONSE_CODE), 2) TICKET_MEDIO,
       ROUND(MAX(((EXTRACT(HOUR FROM TRANSACTION_END_TIME) -
                 EXTRACT(HOUR FROM TRANSACTION_BEGIN_TIME)) * 3600 +
                 (EXTRACT(MINUTE FROM TRANSACTION_END_TIME) -
                 EXTRACT(M INUTE FROM TRANSACTION_BEGIN_TIME)) * 60 +
                 EXTRACT(SECOND FROM TR ANSACTION_END_TIME) -
                 EXTRACT(SECOND FROM TRANSACTION_BEGIN_TIME)) * 1000),
             2) || ' MS' "MAIOR",
       ROUND(MIN(((EXTRACT(HOUR F ROM TRANSACTION_END_TIME) -
                 EXTRACT(HOUR FROM TRANSACTION_BEGIN_T IME)) * 3600 +
                 (EXTRACT(MINUTE FROM TRANSACTION_END_TIME) - EXTRAC
                  T(MINUTE FROM TRANSACTION_BEGIN_TIME)) * 60 +
                 EXTRACT(SECOND FROM TRANSACTION_END_TIME) -
                 EXTRACT(SECOND FROM TRANSACTION_BEGIN_TI ME)) * 1000),
             2) || ' MS' "MENOR",
       ROUND(SUM(((EXTRACT(HOU R FROM TRANSACTION_END_TIME) -
                 EXTRACT(HOUR FROM TRANSACTION_BEGI N_TIME)) * 3600 +
                 (EXTRACT(MINUTE FROM TRANSACTION_END_TIME) - EXT
                  RACT(MINUTE FROM TRANSACTION_BEGIN_TIME)) * 60 +
                 EXTRACT(SECOND F ROM TRANSACTION_END_TIME) -
                 EXTRACT(SECOND FROM TRANSACTION_BEGIN _TIME)) * 1000) /
             COUNT(1),
             2) || ' MS' "MEDIA",
       MAX(OT.TRA NSACTION_BEGIN_TIME) "ULTIMA TRANSACAO",
       MIN(OT.TRANSACTI ON_BEGIN_TIME) "TRANSACAO MAIS ANTIGA"
  FROM AU_OPEN_TRANSACTIO N OT
 INNER JOIN AU_RESPONSE_CODE RC
    ON RC.ID_RESPONSE_CODE = OT.I D_RESPONSE_CODE
 WHERE ID_TRANSACTION > (SELECT min(id_transactio n)
                           FROM (SELECT ID_TRANSACTION F ROM AU_OPEN_TRANSACTION W HERE ID_TRANSACTION > ((SELECT MAX(ID_TRANSACTION) FROM AU_OPEN_T RANSACTION) - 2000 - 5000) ORDER BY 1 DESC)
                          WHERE ROWNUM <= 5000)
 GROUP BY OT.ID_RESPONSE_CODE || ' -
' || RC.DESCRIPTION
 ORDER BY 1 DESC
/
